version: '3.7'
services:
  rbp-booking:
    image: sdetschool/restfulbookerplatform_booking:1.6.a1fd0e5
    ports:
      - "3000:3000"
    restart: always
  rbp-room:
    image: sdetschool/restfulbookerplatform_room:1.6.a1fd0e5
    ports:
      - "3001:3001"
    restart: always
  rbp-branding:
    image: sdetschool/restfulbookerplatform_branding:1.6.a1fd0e5
    ports:
      - "3002:3002"
    restart: always
  rbp-assets:
    image: sdetschool/restfulbookerplatform_assets:1.6.a1fd0e5
    ports:
      - "3003:3003"
    restart: always
  rbp-auth:
    image: sdetschool/restfulbookerplatform_auth:1.6.a1fd0e5
    ports:
      - "3004:3004"
    restart: always
  rbp-report:
    image: sdetschool/restfulbookerplatform_report:1.6.a1fd0e5
    ports:
      - "3005:3005"
    restart: always
  rbp-message:
    image: sdetschool/restfulbookerplatform_message:1.6.a1fd0e5
    ports:
      - "3006:3006"
    restart: always
  rbp-proxy:
    image: sdetschool/restfulbookerplatform_proxy:latest
    ports:
      - "80:80"
    restart: always
